# Generated by Django 2.2.4 on 2022-12-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apppost', '0002_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='users',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='apppost.User'),
            preserve_default=False,
        ),
    ]
